version: 2.4.{build}
image: 
- Visual Studio 2019
platform: x64
configuration: Release
# environment:
#   GOLDDRIVE_HOST:
#     secure: 7iZ2lKF24FhwxW8mL+OMc4xTfkBmY38eqxs91LpZL8Y=
#   GOLDDRIVE_PORT:
#     secure: HiCVHHHiwJUZo8jML2cStQ==
#   GOLDDRIVE_PASS:
#     secure: 25BPcFmVEe3pnXeQiOkyzw==
install:
  - appveyor DownloadFile https://github.com/billziss-gh/winfsp/releases/download/v1.6/winfsp-1.6.20027.msi
  - start /wait msiexec /i winfsp-1.6.20027.msi /qn ADDLOCAL=ALL
  # - ps: Write-host "Rebooting..." 
  # - ps: Restart-Computer -Force 
  # - ps: Start-Sleep -s 1
  # Install the OpenSSH
  # - ps: Get-WindowsCapability -Online | ? Name -like 'OpenSSH*'
  # - ps: Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0
  # - ps: Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
  # - ps: Get-WindowsCapability -Online | ? Name -like 'OpenSSH*'
  # - ps: Set-Service -Name sshd -StartupType 'Automatic'
  # - ps: Start-Service sshd
  # - ps: Get-NetFirewallRule -Name *ssh*
  # - ps: New-NetFirewallRule -Name sshd -DisplayName 'OpenSSH Server (sshd)' -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort 22
  - ps: wsl --list
  - ps: wsl apt-get update
  - ps: wsl apt-get remove --purge openssh-server # First remove sshd with --purge option.
  - ps: wsl apt-get install openssh-server
  - ps: wsl service ssh --full-restart

build_script:
  - msbuild src\golddrive.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /verbosity:minimal
  - start /wait msiexec /i src\build\Release\golddrive-*.msi /qn

# test: off
test:
  # only assemblies to test
  assemblies:
    only:
      - golddrive-test.dll
  # only categories to test
  categories:
    only:
      - Appveyor