version: 2.7.0.{build}
image: 
  - Visual Studio 2019
platform: x64
configuration: Release
install:
  - appveyor DownloadFile https://github.com/billziss-gh/winfsp/releases/download/v1.6/winfsp-1.6.20027.msi
  - start /wait msiexec /i winfsp-1.6.20027.msi /qn ADDLOCAL=ALL
  - wslconfig /u Ubuntu-18.04
  - rd /s /q C:\WSL\Ubuntu1804
  - ps: tools\setup_wsl.ps1
  - C:\Python38\python -m pip install --disable-pip-version-check paramiko pyyaml psutil >NUL
  - C:\Python38\python tools\setupssh.py support@localhost support
build_script:
  - msbuild src\golddrive.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /verbosity:quiet
  - start /wait msiexec /i src\build\Release\golddrive-2.7.0.msi /qn
  - src\build\Release\golddrive.exe --version
test:
  categories:
    only:
      - Appveyor
after_test:
  - ps: |
      net use Z: \\golddrive\support@localhost
      Z:; cd Z:\tmp; echo hello > test.txt; dir; cd
  - ps: |
      $sw = [Diagnostics.Stopwatch]::StartNew()
      C:\projects\golddrive\tools\fstools\fsx.exe -N 10000 test xxxxxx
      $sw.Stop(); Write-host "Time: " $sw.Elapsed.totalseconds
  - ps: |
      $sw = [Diagnostics.Stopwatch]::StartNew()
      C:\projects\golddrive\tools\fstools\fsx.exe -N 10000 -L test xxxxxx
      $sw.Stop(); Write-host "Time: " $sw.Elapsed.totalseconds
  - ps: |
      $sw = [Diagnostics.Stopwatch]::StartNew()
      C:\projects\golddrive\tools\fstools\fsbench-x64.exe -rdwr_cc_* -mmap_* -file_attr* -file_list_single* -file_list_none* -rdwr_nc_*
      $sw.Stop(); Write-host "Time: " $sw.Elapsed.totalseconds
  - ps: |
      $sw = [Diagnostics.Stopwatch]::StartNew()
      C:\projects\golddrive\tools\iozone\iozone.exe -i0 -i1 -i2 -s 1m -s10m -r1m
      $sw.Stop(); Write-host "Time: " $sw.Elapsed.totalseconds
  - ps: |
      net use Z: /d
  #- C:\projects\golddrive\tools\testfs.bat
artifacts:
  - path: src\build\Release\golddrive-2.*.msi
    name: Golddrive
