version: 1.0.{build}
image: Visual Studio 2015
environment:
  WINFSP: winfsp-1.4.18270
install:
- appveyor DownloadFile https://github.com/billziss-gh/winfsp/releases/download/v1.4B3/%WINFSP%.msi
- start /wait msiexec /i %WINFSP%.msi /qn ADDLOCAL=ALL
- cmd: echo Rebooting...
- ps: Restart-Computer -Force
- ps: Start-Sleep -s 60
- cmd: echo Reboot complete.
build:
  project: src\golddrive.sln
  verbosity: minimal


