# golddrive
version: 2.26.{build}
image: 
  - Visual Studio 2019
  - Visual Studio 2022
  - Visual Studio 2017
  - Visual Studio 2015
platform: 
  - x64
  - x86
configuration: 
  - Release
clone_depth: 1
cache:
  - C:\cache
matrix:
  # fast_finish: true
  allow_failures:
    - image: Visual Studio 2022
    - image: Visual Studio 2017
    - image: Visual Studio 2015

install:
  - dir C:\cache >nul 2>&1 || mkdir C:\cache
  - ps: $env:VERSION = C:\Python37\python -c "import re; print(re.search(r'<MyVersion>([0-9\.]+)</MyVersion>.+', open('src\\version.xml').read().replace('\n','')).group(1))" | Out-String
  - echo Version=%VERSION% Configuration=%CONFIGURATION% Platform=%PLATFORM%
    
for:
  -
    matrix:
      only:
        - image: Visual Studio 2022
        - image: Visual Studio 2019

    before_build:
      - start /wait msiexec /i vendor\winfsp\winfsp-1.10.22006.msi /qn ADDLOCAL=ALL
      - wslconfig /u Ubuntu-18.04
      - ps: tools\setup_wsl.ps1
      - C:\Python37\python -m pip install --disable-pip-version-check paramiko >NUL
      - C:\Python37\python tools\setupssh.py support@localhost support
    build_script:
      - msbuild src\golddrive.sln -p:Configuration=%CONFIGURATION% -m /verbosity:quiet /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
      - src\.build\%CONFIGURATION%\%PLATFORM%\golddrive.exe --version
      - start /wait msiexec /i src\.build\%CONFIGURATION%\%PLATFORM%\golddrive-%VERSION%-%PLATFORM%.msi /qn
      - if %PLATFORM% == x64 call "c:\Program Files\Golddrive\golddrive.exe" --version
      - if %PLATFORM% == x86 call "c:\Program Files (x86)\Golddrive\golddrive.exe" --version
      #  - reg query HKLM\Software\WOW6432Node\WinFsp\Services\golddrive /s
    test_script:
      - tools\test.bat
      - ps: |
          net use Z: \\golddrive\support@localhost
          Z:; cd Z:\tmp; echo hello > test.txt; cd
      - ps: |
          $sw = [Diagnostics.Stopwatch]::StartNew()
          C:\projects\golddrive\vendor\fstools\fsx.exe -N 5000 test xxxxxx
          if %PLATFORM% == x64 call C:\projects\golddrive\vendor\fstools\fsbench-x64.exe --files=100 -rdwr_cc_* -mmap_* -file_attr* -file_list_single* -file_list_none* -rdwr_nc_*
          C:\projects\golddrive\vendor\iozone\iozone.exe -s100m -r2m -r4m -r8m
          $sw.Stop(); Write-host "Time: " $sw.Elapsed.totalseconds
      # - ps: get-content -tail 30 $env:LOCALAPPDATA\golddrive\golddrive.log
      - ps: |
          C:; net use Z: /d
    artifacts:
      - path: src\.build\$(configuration)\$(platform)\golddrive-*.msi
        name: msi
      - path: src\.build\$(configuration)\$(platform)\golddrive-*-$(platform).exe
        name: exe
  
  -
    matrix:
      only:
        - image: Visual Studio 2017
        - image: Visual Studio 2015
  
    build_script:
      - ps: Start-FileDownload "https://ci.appveyor.com/api/projects/sganis/golddrive/artifacts/src/.build/$env:CONFIGURATION/$env:PLATFORM/golddrive-$env:VERSION-$env:PLATFORM.exe?branch=master&job=Image%3A%20Visual%20Studio%202019"
      - if exist golddrive-%VERSION%-%PLATFORM%.exe start /wait golddrive-%VERSION%-%PLATFORM%.exe /s /qn 
      - if %PLATFORM% == x64 call "c:\Program Files\Golddrive\golddrive.exe" --version"
      - if %PLATFORM% == x86 call "c:\Program Files (x86)\Golddrive\golddrive.exe" --version"
    test: off
