version: 2.10.0.{build}
image: 
  - Visual Studio 2019
  # - Visual Studio 2017
  # - Visual Studio 2015
  # - Visual Studio 2013
platform: 
  - x64
  # - x86
configuration: 
  - Release222
  - Release2
  - Release
  # - Debug
cache:
  - C:\cache
matrix:
  fast_finish: true
  allow_failures:
    - platform: x86
    - configuration: Debug
    - configuration: Release2
    - image: Visual Studio 2017
    - image: Visual Studio 2015
    - image: Visual Studio 2013
  exclude:
    - configuration: Debug
      platform: x86
    - configuration: Debug
      image: Visual Studio 2017
    - configuration: Debug
      image: Visual Studio 2015
    - configuration: Debug
      image: Visual Studio 2013
install:
  # - dir /b C:\cache || mkdir C:\cache
  - set winfsp=winfsp-1.6.20027.msi
  - if not exist C:\cache\winfsp-1.6.20027.msi (   
      appveyor DownloadFile https://github.com/billziss-gh/winfsp/releases/download/v1.6/winfsp-1.6.20027.msi -FileName C:\cache\winfsp-1.6.20027.msi
    )
  - start /wait msiexec /i C:\cache\winfsp-1.6.20027.msi /qn ADDLOCAL=ALL
  - ps: $env:VERSION = C:\Python37\python -c "import re; print(re.search(r'<MyVersion>([0-9\.]+)</MyVersion>.+', open('src\\version.xml').read().replace('\n','')).group(1))" | Out-String
  - echo Version=%VERSION% Configuration=%CONFIGURATION% Platform=%PLATFORM%
build_script:
  - msbuild src\golddrive.sln -p:Configuration=%CONFIGURATION% -m:4 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - src\build\%CONFIGURATION%\%PLATFORM%\golddrive.exe --version
  - start /wait msiexec /i src\build\%CONFIGURATION%\%PLATFORM%\golddrive-%VERSION%-%PLATFORM%.msi /qn
  - if %PLATFORM% == x64 call "c:\Program Files\Golddrive\golddrive.exe" --version"
  - if %PLATFORM% == x86 call "c:\Program Files (x86)\Golddrive\golddrive.exe" --version"
#  - reg query HKLM\Software\WOW6432Node\WinFsp\Services\golddrive /s
test: off

for:
  -
    matrix:
      only:
        - image: Visual Studio 2019
          configuration: Release
          platform: x64
        - image: Visual Studio 2019
          configuration: Release2
          platform: x64
        - image: Visual Studio 2019
          configuration: Release222
          platform: x64
    before_build:
      # uninstall and setup my own wsl
      - wslconfig /u Ubuntu-18.04
      #- rd /s /q C:\WSL\Ubuntu1804
      - ps: tools\setup_wsl.ps1
      - C:\Python37\python -m pip install --disable-pip-version-check paramiko pyyaml psutil >NUL
      - C:\Python37\python tools\setupssh.py support@localhost support
    test: 
      categories:
        only:
          - Appveyor
    after_test:
      - ps: |
          net use Z: \\golddrive\support@localhost
          Z:; cd Z:\tmp; echo hello > test.txt; cd
      - ps: |
          $sw = [Diagnostics.Stopwatch]::StartNew()
          C:\projects\golddrive\tools\fstools\fsx.exe -N 5000 test xxxxxx
          C:\projects\golddrive\tools\fstools\fsbench-x64.exe --files=100 -rdwr_cc_* -mmap_* -file_attr* -file_list_single* -file_list_none* -rdwr_nc_*
          C:\projects\golddrive\tools\iozone\iozone.exe -i0 -i1 -i2 -s1m -s10m -s100m -r1m
          $sw.Stop(); Write-host "Time: " $sw.Elapsed.totalseconds
      - ps: get-content -tail 30 $env:LOCALAPPDATA\golddrive\golddrive.log
      - ps: |
          C:; net use Z: /d
  -
    matrix:
      only:
        - image: Visual Studio 2017
        - image: Visual Studio 2015
        - image: Visual Studio 2013
    build: off
    test_script:
      - ps: Start-FileDownload "https://ci.appveyor.com/api/projects/sganis/golddrive/artifacts/src/build/$env:CONFIGURATION/$env:PLATFORM/golddrive-$env:VERSION-$env:PLATFORM.msi?branch=master&job=Image%3A%20Visual%20Studio%202019%3B%20Configuration%3A%20Release%3B%20Platform%3A%20$env:PLATFORM"
      - start /wait msiexec /i golddrive-%VERSION%-%PLATFORM%.msi /qn 
      - if %PLATFORM% == x64 call "c:\Program Files\Golddrive\golddrive.exe" --version"
      - if %PLATFORM% == x86 call "c:\Program Files (x86)\Golddrive\golddrive.exe" --version"

artifacts:
  - path: src\build\$(configuration)\$(platform)\golddrive-*.msi
    name: Golddrive
