version: 2.0.{build}
image: 
- Visual Studio 2017
platform: x64
configuration: Release
environment:
  GOLDDRIVE_HOST:
    secure: 7iZ2lKF24FhwxW8mL+OMc4xTfkBmY38eqxs91LpZL8Y=
  GOLDDRIVE_PORT:
    secure: HiCVHHHiwJUZo8jML2cStQ==
  GOLDDRIVE_PASS:
    secure: 25BPcFmVEe3pnXeQiOkyzw==
install:
  - net use
  - start /wait msiexec /i src\bundle\winfsp\winfsp-1.4.19049.msi /qn ADDLOCAL=ALL
  - ps: Restart-Computer -Force 
  - ps: Start-Sleep -s 10
  - ps: Write-host "Reboot complete." 
  # - appveyor DownloadFile https://github.com/billziss-gh/winfsp/releases/download/v1.4B3/%WINFSP%.msi
build_script:
  - msbuild src\golddrive.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /verbosity:minimal
  - start /wait msiexec /i src\build\Release\golddrive-*.msi /qn
  - C:\Python37\python -m pip install paramiko
  - echo "test host %GOLDDRIVE_HOST%"
  - C:\Python37\python tools\setupssh.py support@%GOLDDRIVE_HOST%:%GOLDDRIVE_PORT%
test: off
# test_script:
#   - set GOLDDRIVE_HOST=%my_ip%
#   - set GOLDDRIVE_PASS=%my_variable%
#   - set GOLDDRIVE_USER=support
#   - set GOLDDRIVE_PORT=%my_port%
#   - vstest.console /logger:Appveyor src\test\bin\Release\golddrive-test.dll  # categories:

