version: 1.0.{build}
image: 
- Visual Studio 2017
# - Ubuntu
platform: x64
configuration: Release
environment:
  # APPVEYOR_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGlxioqCbDubblzttEHvEMJ5rspJZ7JpcMSeHNGEui17hxcIZKfgS5xpAG3W1gLRo191SZS2NkNZwW5P39SWF/kBvXyVPiCu9E6q5FuwtYZXr0SKUtca8/V5s6UGeKMATDCNl6iuBTa4R7xa6ubEho8UykmY8dHKzuqas4RXSL31QUD2AFbmzGVV0wHxOobrTEGeLzILIfhC9QxjeAo+uD+KWpTN46ilcivvpMtG4rnQ7C8NgdZyzVT0f+RIYa6HCRTL2O+vVvG0AnHVkatY2Cpgtv2K7thQCINjoM8JlDicDtaOOCxkiB++KbbJJt00db9lpxv9Oumdke5p2GzStH
  GOLDDRIVE_HOST: localhost
  GOLDDRIVE_PASS: support
  GOLDDRIVE_USER: support
  GOLDDRIVE_PORT: 2222
  WINFSP: winfsp-1.4.18270
install:
  - docker version
  - appveyor DownloadFile https://github.com/billziss-gh/winfsp/releases/download/v1.4B3/%WINFSP%.msi
  - start /wait msiexec /i %WINFSP%.msi /qn ADDLOCAL=ALL
  # - choco install -y docker
  # - choco install -y docker-machine
  - ps: Restart-Computer -Force 
  # - ps: Start-Sleep -s 60 
  - ps: Write-host "Reboot complete." 
  - C:\Python37\python -m pip install --upgrade paramiko pytest
build:
  project: src\golddrive.sln
  verbosity: minimal
before_test:
  - cd docker
  - docker build -t ssh-server .
  - docker run --rm -d -p 2222:22 -t ssh-server
test_script:
  - set PATH=C:\Python37;C:\Python37\Scripts;%PATH%
  - cd test
  - pytest

# for:
# # Windows only
# -
#   matrix:
#     only:
#       - image: Visual Studio 2015
#   install:
#     - cmd: appveyor DownloadFile https://github.com/billziss-gh/winfsp/releases/download/v1.4B3/%WINFSP%.msi
#     - cmd: start /wait msiexec /i %WINFSP%.msi /qn ADDLOCAL=ALL
#     - ps: if ($isWindows) { Restart-Computer -Force }
#     - ps: if ($isWindows) { Start-Sleep -s 60 }
#     - ps: if ($isWindows) { Write-host "Reboot complete." }
#   build:
#     project: src\golddrive.sln
#     verbosity: minimal
# Ubuntu
# -
#   matrix:
#     only:
#       - image: Ubuntu
#   build_script:
#   - echo Ubuntu build script
#   - docker version
#   - cd docker
#   - docker build -t ssh-server .
#   - docker run --rm -d -p 2222:22 -t ssh-server
#   after_build:
#   # - export APPVEYOR_SSH_BLOCK=true
#   # - curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
