version: 2.2.{build}
image: 
- Visual Studio 2019
platform: x64
configuration: Release
environment:
  GOLDDRIVE_HOST:
    secure: 7iZ2lKF24FhwxW8mL+OMc4xTfkBmY38eqxs91LpZL8Y=
  GOLDDRIVE_PORT:
    secure: HiCVHHHiwJUZo8jML2cStQ==
  GOLDDRIVE_PASS:
    secure: 25BPcFmVEe3pnXeQiOkyzw==
install:
  - start /wait msiexec /i src\bundle\winfsp\winfsp-1.5.19090.msi /qn ADDLOCAL=ALL
  - ps: Write-host "Rebooting..." 
  - ps: Restart-Computer -Force 
  - ps: Start-Sleep -s 1
  # - appveyor DownloadFile https://github.com/billziss-gh/winfsp/releases/download/v1.4B3/%WINFSP%.msi
build_script:
  - msbuild src\golddrive.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /verbosity:minimal
  - start /wait msiexec /i src\build\Release\golddrive-*.msi /qn
  # - C:\Python37\python -m pip install paramiko pyyaml psutil
  # - echo "test host %GOLDDRIVE_HOST%"
test:
#   - vstest.console /logger:Appveyor src\test\bin\Release\golddrive-test.dll  # categories:
  categories:
    - Appveyor
