# golddrive
version: 2.6.{build}
image: Visual Studio 2022
platform: x64
configuration: Release
clone_depth: 1
cache:
  - C:\cache

install:
  - dir C:\cache >nul 2>&1 || mkdir C:\cache
  - choco install innosetup -y --no-progress
  - dotnet --version
  - ps: $env:VERSION = python -c "import re; print(re.search(r'<MyVersion>([0-9\.]+)</MyVersion>.+', open('src\\version.xml').read().replace('\n','')).group(1))" | Out-String
  - echo Version=%VERSION% Configuration=%CONFIGURATION% Platform=%PLATFORM%

artifacts:
  - path: build\$(configuration)\$(platform)\golddrive-*-setup.exe
    name: setup

build_script:
  - start /wait msiexec /i vendor\winfsp\winfsp-2.1.25156.msi /qn ADDLOCAL=ALL
  - wslconfig /u Ubuntu-18.04
  - ps: tools\setup_wsl.ps1
  - python -m pip install --disable-pip-version-check paramiko >NUL
  - python tools\setupssh.py support@localhost support
  - msbuild src\cli\cli.vcxproj /t:rebuild /p:Configuration=%CONFIGURATION% /p:Platform=%PLATFORM% /p:SolutionDir=%CD%\src\ /v:minimal
  - dotnet build src\app\app.csproj -c %CONFIGURATION% -o build\%CONFIGURATION%\%PLATFORM%
  - dotnet build src\test\test.csproj -c %CONFIGURATION% -o build\%CONFIGURATION%\%PLATFORM%
  - build\%CONFIGURATION%\%PLATFORM%\golddrive.exe --version
  - '"%ProgramFiles(x86)%\Inno Setup 6\ISCC.exe" /DMyAppVersion=%VERSION% /DMyPlatform=%PLATFORM% /DMyConfiguration=%CONFIGURATION% installer\setup.iss'
  - build\%CONFIGURATION%\%PLATFORM%\golddrive-%VERSION%-%PLATFORM%-setup.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  - call "c:\Program Files\Golddrive\golddrive.exe" --version

test_script:
  - tools\test.bat
  - ps: |
      net use Z: \\golddrive\support@localhost
      Z:; cd Z:\tmp; echo hello > test.txt; cd
  - ps: |
      $sw = [Diagnostics.Stopwatch]::StartNew()
      C:\projects\golddrive\vendor\fstools\fsx.exe -N 5000 test xxxxxx
      C:\projects\golddrive\vendor\fstools\fsbench-x64.exe --files=100 -rdwr_cc_* -mmap_* -file_attr* -file_list_single* -file_list_none* -rdwr_nc_*
      C:\projects\golddrive\vendor\iozone\iozone.exe -s100m -r2m
      $sw.Stop(); Write-host "Time: " $sw.Elapsed.totalseconds
  - ps: |
      C:; net use Z: /d
