# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 719)
        MainWindow.setMinimumSize(QtCore.QSize(350, 0))
        MainWindow.setMaximumSize(QtCore.QSize(500, 800))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_4.setContentsMargins(50, 11, 50, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_6 = QtWidgets.QWidget(self.centralWidget)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pbHamburger = QtWidgets.QPushButton(self.widget_6)
        self.pbHamburger.setMaximumSize(QtCore.QSize(32, 32))
        self.pbHamburger.setText("")
        self.pbHamburger.setObjectName("pbHamburger")
        self.horizontalLayout_5.addWidget(self.pbHamburger)
        self.label = QtWidgets.QLabel(self.widget_6)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.verticalLayout_4.addWidget(self.widget_6)
        self.lblUserHostPort = QtWidgets.QLabel(self.centralWidget)
        self.lblUserHostPort.setAlignment(QtCore.Qt.AlignCenter)
        self.lblUserHostPort.setObjectName("lblUserHostPort")
        self.verticalLayout_4.addWidget(self.lblUserHostPort)
        self.widget_3 = QtWidgets.QWidget(self.centralWidget)
        self.widget_3.setObjectName("widget_3")
        self.hboxlayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.hboxlayout.setContentsMargins(11, 11, 11, 11)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")
        self.cboParam = QtWidgets.QComboBox(self.widget_3)
        self.cboParam.setObjectName("cboParam")
        self.hboxlayout.addWidget(self.cboParam)
        self.verticalLayout_4.addWidget(self.widget_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.widget_7 = QtWidgets.QWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setMinimumSize(QtCore.QSize(0, 130))
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_2.setContentsMargins(0, 11, 0, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblStatus = QtWidgets.QLabel(self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblStatus.sizePolicy().hasHeightForWidth())
        self.lblStatus.setSizePolicy(sizePolicy)
        self.lblStatus.setMinimumSize(QtCore.QSize(0, 20))
        self.lblStatus.setMaximumSize(QtCore.QSize(16777215, 150))
        self.lblStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.lblStatus.setWordWrap(True)
        self.lblStatus.setObjectName("lblStatus")
        self.verticalLayout_2.addWidget(self.lblStatus)
        self.widgetPassword = QtWidgets.QWidget(self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetPassword.sizePolicy().hasHeightForWidth())
        self.widgetPassword.setSizePolicy(sizePolicy)
        self.widgetPassword.setMinimumSize(QtCore.QSize(0, 120))
        self.widgetPassword.setMaximumSize(QtCore.QSize(16777215, 120))
        self.widgetPassword.setStyleSheet("")
        self.widgetPassword.setObjectName("widgetPassword")
        self._2 = QtWidgets.QVBoxLayout(self.widgetPassword)
        self._2.setContentsMargins(11, 11, 11, 11)
        self._2.setSpacing(0)
        self._2.setObjectName("_2")
        self.txtPassword = QtWidgets.QLineEdit(self.widgetPassword)
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPassword.setObjectName("txtPassword")
        self._2.addWidget(self.txtPassword)
        self.widget_8 = QtWidgets.QWidget(self.widgetPassword)
        self.widget_8.setStyleSheet("border: 0px")
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_6.setContentsMargins(11, 0, 0, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.pbCancel = QtWidgets.QPushButton(self.widget_8)
        self.pbCancel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pbCancel.setObjectName("pbCancel")
        self.horizontalLayout_6.addWidget(self.pbCancel)
        self._2.addWidget(self.widget_8)
        self.verticalLayout_2.addWidget(self.widgetPassword)
        self.verticalLayout_4.addWidget(self.widget_7)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.widget_2 = QtWidgets.QWidget(self.centralWidget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(58, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_4 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 8))
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 8))
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progressBar = QtWidgets.QProgressBar(self.widget_4)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 2))
        self.progressBar.setMaximum(0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.verticalLayout.addWidget(self.widget_4)
        self.pbConnect = QtWidgets.QPushButton(self.widget)
        self.pbConnect.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pbConnect.setObjectName("pbConnect")
        self.verticalLayout.addWidget(self.pbConnect)
        self.horizontalLayout_3.addWidget(self.widget)
        spacerItem4 = QtWidgets.QSpacerItem(59, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_4.addWidget(self.widget_2)
        self.widget_5 = QtWidgets.QWidget(self.centralWidget)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lblSettings = QtWidgets.QLabel(self.widget_5)
        self.lblSettings.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lblSettings.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lblSettings.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSettings.setObjectName("lblSettings")
        self.horizontalLayout_4.addWidget(self.lblSettings)
        self.verticalLayout_4.addWidget(self.widget_5)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblUserHostPort.setText(_translate("MainWindow", "user@host:port"))
        self.lblStatus.setText(_translate("MainWindow", "Status"))
        self.txtPassword.setPlaceholderText(_translate("MainWindow", "Password"))
        self.pbCancel.setText(_translate("MainWindow", "CANCEL"))
        self.pbConnect.setText(_translate("MainWindow", "CONNECT"))
        self.lblSettings.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"#\"><span style=\" text-decoration: underline; color:#0000ff;\">Config Folder</span></a></p></body></html>"))

