# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\assets\ui\app.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(459, 630)
        MainWindow.setMinimumSize(QtCore.QSize(350, 0))
        MainWindow.setMaximumSize(QtCore.QSize(500, 800))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_4.setContentsMargins(50, 11, 50, 11)
        self.verticalLayout_4.setSpacing(12)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_1_top = QtWidgets.QWidget(self.centralWidget)
        self.widget_1_top.setObjectName("widget_1_top")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_1_top)
        self.horizontalLayout_5.setContentsMargins(11, 11, 0, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.widget_1_top)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.pbHamburger = QtWidgets.QPushButton(self.widget_1_top)
        self.pbHamburger.setMaximumSize(QtCore.QSize(32, 32))
        self.pbHamburger.setText("")
        self.pbHamburger.setObjectName("pbHamburger")
        self.horizontalLayout_5.addWidget(self.pbHamburger)
        self.verticalLayout_4.addWidget(self.widget_1_top)
        self.widget_2_combo = QtWidgets.QWidget(self.centralWidget)
        self.widget_2_combo.setObjectName("widget_2_combo")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2_combo)
        self.verticalLayout_2.setContentsMargins(0, 11, 0, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cboParam = QtWidgets.QComboBox(self.widget_2_combo)
        self.cboParam.setObjectName("cboParam")
        self.verticalLayout_2.addWidget(self.cboParam)
        self.widget_3_settings = QtWidgets.QWidget(self.widget_2_combo)
        self.widget_3_settings.setObjectName("widget_3_settings")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3_settings)
        self.horizontalLayout_2.setContentsMargins(0, 0, 4, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.lblSettings = QtWidgets.QLabel(self.widget_3_settings)
        self.lblSettings.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lblSettings.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lblSettings.setObjectName("lblSettings")
        self.horizontalLayout_2.addWidget(self.lblSettings)
        self.verticalLayout_2.addWidget(self.widget_3_settings)
        self.lblUserHostPort = QtWidgets.QLabel(self.widget_2_combo)
        self.lblUserHostPort.setAlignment(QtCore.Qt.AlignCenter)
        self.lblUserHostPort.setObjectName("lblUserHostPort")
        self.verticalLayout_2.addWidget(self.lblUserHostPort)
        self.verticalLayout_4.addWidget(self.widget_2_combo)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralWidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageMain = QtWidgets.QWidget()
        self.pageMain.setObjectName("pageMain")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.pageMain)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblMessage = QtWidgets.QLabel(self.pageMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMessage.sizePolicy().hasHeightForWidth())
        self.lblMessage.setSizePolicy(sizePolicy)
        self.lblMessage.setAlignment(QtCore.Qt.AlignCenter)
        self.lblMessage.setWordWrap(True)
        self.lblMessage.setObjectName("lblMessage")
        self.verticalLayout_3.addWidget(self.lblMessage)
        self.widget_2 = QtWidgets.QWidget(self.pageMain)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(58, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pbConnect = QtWidgets.QPushButton(self.widget_2)
        self.pbConnect.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pbConnect.setObjectName("pbConnect")
        self.horizontalLayout.addWidget(self.pbConnect)
        spacerItem2 = QtWidgets.QSpacerItem(59, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.stackedWidget.addWidget(self.pageMain)
        self.pageHost = Host()
        self.pageHost.setObjectName("pageHost")
        self.stackedWidget.addWidget(self.pageHost)
        self.pageLogin = Login()
        self.pageLogin.setObjectName("pageLogin")
        self.stackedWidget.addWidget(self.pageLogin)
        self.pageAbout = About()
        self.pageAbout.setObjectName("pageAbout")
        self.stackedWidget.addWidget(self.pageAbout)
        self.verticalLayout_4.addWidget(self.stackedWidget)
        self.widget_8_progress = QtWidgets.QWidget(self.centralWidget)
        self.widget_8_progress.setObjectName("widget_8_progress")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_8_progress)
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.progressBar = QtWidgets.QProgressBar(self.widget_8_progress)
        self.progressBar.setMaximumSize(QtCore.QSize(150, 2))
        self.progressBar.setMaximum(0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_6.addWidget(self.progressBar)
        self.verticalLayout_4.addWidget(self.widget_8_progress)
        self.widget_9_bottom = QtWidgets.QWidget(self.centralWidget)
        self.widget_9_bottom.setObjectName("widget_9_bottom")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_9_bottom)
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_4.addWidget(self.widget_9_bottom)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblSettings.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"#\"><span style=\" text-decoration: none; color:#0E639C;\">Settings</span></a></p></body></html>"))
        self.lblUserHostPort.setText(_translate("MainWindow", "user@host:port"))
        self.lblMessage.setText(_translate("MainWindow", "Message"))
        self.pbConnect.setText(_translate("MainWindow", "CONNECT"))

from about import About
from host import Host
from login import Login
import resources_rc
